#!/bin/bash
# build-ios-sim-template.sh
# Build a custom Godot iOS simulator export template from source, patch the
# official ios.zip to swap the broken x86_64 sim slice for a real arm64 sim .a,
# and install the patched template into the Godot 4.6.3 export template folder.
#
# This script is for the Tower Defence project, but should work for any Godot
# 4.6.x project that wants iOS simulator support.
#
# Status (2026-06-09): the sim .a builds successfully, but the .xcodeproj
# generated by `godot --export-debug iOS` does not link correctly when targeting
# iphonesimulator (Swift Concurrency symbols in godot_swift_module are unresolved).
# So this script gets us 90% of the way; the last 10% is upstream.
#
# See docs/ios-sim-build.md for full context.

set -euo pipefail

GODOT_VERSION="${GODOT_VERSION:-4.6.3-stable}"
BUILD_DIR="${BUILD_DIR:-/tmp/godot-${GODOT_VERSION}-build}"
SIM_UUID="${SIM_UUID:-DB94ECCE-F5B6-4F33-AB1F-6EBE5A8576CD}"   # iPhone 17 Pro
TEMPLATE_DEST="$HOME/Library/Application Support/Godot/export_templates/${GODOT_VERSION%.*}.stable"

echo "=== 1. Clone Godot $GODOT_VERSION source (if not already present) ==="
mkdir -p "$BUILD_DIR"
if [ ! -d "$BUILD_DIR/godot/.git" ]; then
  echo "Cloning..."
  git clone --depth 1 --branch "$GODOT_VERSION" https://github.com/godotengine/godot.git "$BUILD_DIR/godot"
else
  echo "Already cloned at $BUILD_DIR/godot"
  cd "$BUILD_DIR/godot"
  git fetch --depth 1 origin "$GODOT_VERSION" 2>/dev/null || true
  git checkout "$GODOT_VERSION" 2>/dev/null || true
fi

echo ""
echo "=== 2. Build the iOS arm64 sim template (takes 20-40 min on M-series) ==="
cd "$BUILD_DIR/godot"
/opt/homebrew/bin/scons platform=ios target=template_release ios_simulator=yes arch=arm64 -j9 2>&1 | tail -20

SIM_A="$BUILD_DIR/godot/bin/libgodot.ios.template_release.arm64.simulator.a"
if [ ! -f "$SIM_A" ]; then
  echo "❌ Sim .a not produced at $SIM_A"
  exit 1
fi
echo "✓ Built: $SIM_A ($(stat -f%z $SIM_A) bytes)"

echo ""
echo "=== 3. Backup the official template and unzip it ==="
OFFICIAL="$TEMPLATE_DEST/ios.zip"
if [ ! -f "$OFFICIAL" ]; then
  echo "❌ Official template not found: $OFFICIAL"
  exit 1
fi
TS=$(date +%Y%m%d-%H%M%S)
cp -p "$OFFICIAL" "$OFFICIAL.bak.$TS"
echo "Backup: $OFFICIAL.bak.$TS"

WORK=/tmp/td-template-patch
rm -rf "$WORK" && mkdir -p "$WORK"
cd "$WORK"
unzip -q "$OFFICIAL"

echo ""
echo "=== 4. Swap the sim slice in the release xcframework ==="
SLICE=libgodot.ios.release.xcframework/ios-arm64_x86_64-simulator
OLD_SIZE=$(stat -f%z "$SLICE/libgodot.a")
cp "$SIM_A" "$SLICE/libgodot.a"
echo "Replaced $SLICE/libgodot.a ($OLD_SIZE → $(stat -f%z $SLICE/libgodot.a) bytes)"

echo ""
echo "=== 5. Update xcframework Info.plist: only declare arm64 for sim slice ==="
python3 <<'PY'
import plistlib, os
path = 'libgodot.ios.release.xcframework/Info.plist'
with open(path, 'rb') as f:
    pl = plistlib.load(f)
changed = False
for lib in pl.get('AvailableLibraries', []):
    if lib.get('SupportedPlatformVariant') == 'simulator':
        if lib.get('SupportedArchitectures') != ['arm64']:
            lib['SupportedArchitectures'] = ['arm64']
            changed = True
            print(f"Updated sim slice {lib['LibraryIdentifier']} to arm64 only")
if changed:
    with open(path, 'wb') as f:
        plistlib.dump(pl, f)
    print("Saved.")
else:
    print("Already correct.")
PY

echo ""
echo "=== 6. Re-zip the patched template and install ==="
cd "$WORK"
rm -f patched_ios.zip
zip -r -q -X patched_ios.zip . -x "official.zip" "patched_ios.zip"
cp patched_ios.zip "$OFFICIAL"
echo "Installed: $OFFICIAL"
echo ""

echo "=== 7. Re-export the project iOS preset (assumes cwd is the project) ==="
godot --headless --export-debug "iOS" "builds/tower-defense-ios.zip" 2>&1 | tail -5

echo ""
echo "=== 8. Patch the regenerated xcframework sim slice in the project ==="
PROJECT_XCFRAMEWORK="builds/tower-defense-ios.xcframework/ios-arm64_x86_64-simulator/libgodot.a"
if [ -f "$PROJECT_XCFRAMEWORK" ]; then
  cp "$SIM_A" "$PROJECT_XCFRAMEWORK"
  echo "Patched: $PROJECT_XCFRAMEWORK"
  lipo -info "$PROJECT_XCFRAMEWORK"
fi

echo ""
echo "=== 9. Try the sim xcodebuild (will likely fail on Swift Concurrency in 4.6.3) ==="
echo "xcodebuild -project builds/tower-defense-ios.xcodeproj -scheme tower-defense-ios \\"
echo "  -configuration Release -destination 'generic/platform=iOS Simulator' \\"
echo "  -derivedDataPath /tmp/td-sim-build ARCHS=arm64 build"
echo "(if it fails, see docs/ios-sim-build.md for upstream context)"
